# Generated by Django 5.1.7 on 2025-03-20 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_created_at'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
            preserve_default=False,
        ),
    ]
